/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_gomint_raknet_PacketDispatcher */

#ifndef _Included_io_gomint_raknet_PacketDispatcher
#define _Included_io_gomint_raknet_PacketDispatcher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_gomint_raknet_PacketDispatcher
 * Method:    jniInstallDispatcher
 * Signature: (JLio/gomint/raknet/PacketDispatcher;)J
 */
JNIEXPORT jlong JNICALL Java_io_gomint_raknet_PacketDispatcher_jniInstallDispatcher
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     io_gomint_raknet_PacketDispatcher
 * Method:    jniUninstallDispatcher
 * Signature: (JLio/gomint/raknet/PacketDispatcher;J)V
 */
JNIEXPORT void JNICALL Java_io_gomint_raknet_PacketDispatcher_jniUninstallDispatcher
  (JNIEnv *, jclass, jlong, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
